# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Check which prevalence samples are valid for each location at each time point.
#' @param prevalence_map List where each element is prevalence_map data for a time point.
#' @param boundaries Vector of length two.
#' @param sd Parameter sigma of the Gaussian kernel.
#' @return An (n_tims x n_locs x m) array.
#' @export
calc_log_norm_const_gaussian <- function(prevalence_map, boundaries, sd) {
    .Call('_AMISforInfectiousDiseases_calc_log_norm_const_gaussian', PACKAGE = 'AMISforInfectiousDiseases', prevalence_map, boundaries, sd)
}

#' @title  Compute weight matrix using empirical Radon-Nikodym derivative (Rcpp version) and Gaussian kernel
#' @description Compute matrix describing the weights for each parameter sampled, for each
#' location. One row per sample, one column per location.  Each weight 
#' is computed based on the empirical Radon-Nikodym derivative, taking into account 
#' geostatistical prevalence data for the specific location and the prevalence values 
#' computed from the transmission model for the specific parameter sample.
#' @param likelihoods An n_sims x n_locs matrix of (log-)likelihoods
#' NB: transpose of slice of array. 
#' @param prev_sim A vector containing the simulated prevalence value for each parameter sample.
#' @param amis_params A list of parameters, e.g. from \code{\link{default_amis_params}}
#' @param weight_matrix An n_sims x n_locs matrix containing the current values of the weights.
#' @param sim_within_boundaries Vector showing which simulated values are within boundaries.
#' @param sim_outside_boundaries Vector showing which simulated values are outside boundaries.
#' @param locs Vector showing which locations have data.
#' @return An updated weight matrix.
#' @export
compute_weight_matrix_empirical_gauss <- function(likelihoods, prev_sim, amis_params, weight_matrix, sim_within_boundaries, sim_outside_boundaries, locs) {
    .Call('_AMISforInfectiousDiseases_compute_weight_matrix_empirical_gauss', PACKAGE = 'AMISforInfectiousDiseases', likelihoods, prev_sim, amis_params, weight_matrix, sim_within_boundaries, sim_outside_boundaries, locs)
}

#' @title  Compute weight matrix using empirical Radon-Nikodym derivative (Rcpp version)
#' @description Compute matrix describing the weights for each parameter sampled, for each
#' location. One row per sample, one column per location.  Each weight 
#' is computed based on the empirical Radon-Nikodym derivative, taking into account 
#' geostatistical prevalence data for the specific location and the prevalence values 
#' computed from the transmission model for the specific parameter sample.
#' @param likelihoods An n_sims x n_locs matrix of (log-)likelihoods
#' NB: transpose of slice of array. 
#' @param prev_sim A vector containing the simulated prevalence value for each parameter sample.
#' @param amis_params A list of parameters, e.g. from \code{\link{default_amis_params}}
#' @param weight_matrix An n_sims x n_locs matrix containing the current values of the weights.
#' @param is_within_boundaries Logical vector showing which simulated values are within boundaries.
#' @param sim_within_boundaries Vector showing which simulated values are within boundaries.
#' @param sim_outside_boundaries Vector showing which simulated values are outside boundaries.
#' @param locs Vector showing which locations have data.
#' @return An updated weight matrix.
#' @export
compute_weight_matrix_empirical_uniform <- function(likelihoods, prev_sim, amis_params, weight_matrix, is_within_boundaries, sim_within_boundaries, sim_outside_boundaries, locs) {
    .Call('_AMISforInfectiousDiseases_compute_weight_matrix_empirical_uniform', PACKAGE = 'AMISforInfectiousDiseases', likelihoods, prev_sim, amis_params, weight_matrix, is_within_boundaries, sim_within_boundaries, sim_outside_boundaries, locs)
}

#' @title Empirical estimator for the likelihood using Gaussian kernel
#' @param prevalence_map An L x M matrix containing samples from the fitted prevalence map.
#' @param prev_sim A vector containing the simulated prevalence value for each parameter sample.
#' @param sd Bandwith value.
#' @param sim_within_boundaries Vector showing which simulated values are within boundaries.
#' @param which_valid_prev_map_t List showing which samples are valid for each location at a time point. 
#' @param log_norm_const_gaussian_t (n_locs x M) matrix showing the log normalising constant for the Gaussian kernels.
#' @param left_boundary Lower boundary for the prevalence.
#' @param right_boundary Upper boundary for the prevalence.
#' @return A matrix with L rows containing the empirical estimates for the likelihood.
#' @export
f_estimator_Gaussian <- function(prevalence_map, prev_sim, sd, sim_within_boundaries, which_valid_prev_map_t, log_norm_const_gaussian_t, left_boundary, right_boundary) {
    .Call('_AMISforInfectiousDiseases_f_estimator_Gaussian', PACKAGE = 'AMISforInfectiousDiseases', prevalence_map, prev_sim, sd, sim_within_boundaries, which_valid_prev_map_t, log_norm_const_gaussian_t, left_boundary, right_boundary)
}

#' @title Empirical estimator for the likelihood using Uniform kernel
#' @param prevalence_map An L x M matrix containing samples from the fitted prevalence map.
#' @param prev_sim A vector containing the simulated prevalence value for each parameter sample.
#' @param delta Bandwidth value.
#' @param sim_within_boundaries Vector showing which simulated values are within boundaries.
#' @param which_valid_prev_map_t List showing which samples are valid for each location at a time point. 
#' @param left_boundary Lower boundary for the prevalence.
#' @param right_boundary Upper boundary for the prevalence.
#' @return A matrix with L rows containing the empirical estimates for the likelihood.
#' @export
f_estimator_uniform <- function(prevalence_map, prev_sim, delta, sim_within_boundaries, which_valid_prev_map_t, left_boundary, right_boundary) {
    .Call('_AMISforInfectiousDiseases_f_estimator_uniform', PACKAGE = 'AMISforInfectiousDiseases', prevalence_map, prev_sim, delta, sim_within_boundaries, which_valid_prev_map_t, left_boundary, right_boundary)
}

#' @title Check which prevalence samples are valid for each location at each time point.
#' @param prevalence_map List where each element is prevalence_map data for a time point.
#' @param boundaries Vector of length two.
#' @return A list where each element corresponds to a time point. For each time point, there will 
#' be a list of n_locs elements, where each one shows which samples (out of M) are valid. 
#' @export
get_which_valid_prev_map <- function(prevalence_map, boundaries) {
    .Call('_AMISforInfectiousDiseases_get_which_valid_prev_map', PACKAGE = 'AMISforInfectiousDiseases', prevalence_map, boundaries)
}

#' @title Check, at each time, which locations have data
#' @param which_valid_prev_map List obtained by get_which_valid_prev_map
#' @param n_tims Number of time points
#' @param n_locs Number of locations
#' @export
get_which_valid_locs_prev_map <- function(which_valid_prev_map, n_tims, n_locs) {
    .Call('_AMISforInfectiousDiseases_get_which_valid_locs_prev_map', PACKAGE = 'AMISforInfectiousDiseases', which_valid_prev_map, n_tims, n_locs)
}

